/*==========================================================================*\
 |  _BatchResult.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to BatchResult.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2009 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package net.sf.webcat.batchprocessor;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * BatchResult.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _BatchResult
    extends er.extensions.eof.ERXGenericRecord
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _BatchResult object.
     */
    public _BatchResult()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * BatchResult object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param isCompleteValue
     * @return The newly created object
     */
    public static BatchResult create(
        EOEditingContext editingContext,
        boolean isCompleteValue
        )
    {
        BatchResult eoObject = (BatchResult)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _BatchResult.ENTITY_NAME);
        eoObject.setIsComplete(isCompleteValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static BatchResult localInstance(
        EOEditingContext editingContext, BatchResult eo)
    {
        return (eo == null)
            ? null
            : (BatchResult)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static BatchResult forId(
        EOEditingContext ec, int id )
    {
        BatchResult obj = null;
        if (id > 0)
        {
            NSArray<BatchResult> results =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (results != null && results.count() > 0)
            {
                obj = results.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static BatchResult forId(
        EOEditingContext ec, String id )
    {
        return forId( ec, er.extensions.foundation.ERXValueUtilities.intValue( id ) );
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String COMPLETED_TIME_KEY = "completedTime";
    public static final ERXKey<NSTimestamp> completedTime =
        new ERXKey<NSTimestamp>(COMPLETED_TIME_KEY);
    public static final String DESCRIPTION_KEY = "description";
    public static final ERXKey<String> description =
        new ERXKey<String>(DESCRIPTION_KEY);
    public static final String IS_COMPLETE_KEY = "isComplete";
    public static final ERXKey<Integer> isComplete =
        new ERXKey<Integer>(IS_COMPLETE_KEY);
    // To-one relationships ---
    public static final String BATCH_PLUGIN_KEY = "batchPlugin";
    public static final ERXKey<net.sf.webcat.batchprocessor.BatchPlugin> batchPlugin =
        new ERXKey<net.sf.webcat.batchprocessor.BatchPlugin>(BATCH_PLUGIN_KEY);
    public static final String OBJECT_QUERY_KEY = "objectQuery";
    public static final ERXKey<net.sf.webcat.core.ObjectQuery> objectQuery =
        new ERXKey<net.sf.webcat.core.ObjectQuery>(OBJECT_QUERY_KEY);
    public static final String USER_KEY = "user";
    public static final ERXKey<net.sf.webcat.core.User> user =
        new ERXKey<net.sf.webcat.core.User>(USER_KEY);
    // To-many relationships ---
    public static final String BATCH_JOBS_KEY = "batchJobs";
    public static final ERXKey<net.sf.webcat.batchprocessor.BatchJob> batchJobs =
        new ERXKey<net.sf.webcat.batchprocessor.BatchJob>(BATCH_JOBS_KEY);
    public static final String FEEDBACK_SECTIONS_KEY = "feedbackSections";
    public static final ERXKey<net.sf.webcat.batchprocessor.BatchFeedbackSection> feedbackSections =
        new ERXKey<net.sf.webcat.batchprocessor.BatchFeedbackSection>(FEEDBACK_SECTIONS_KEY);
    public static final String SAVED_PROPERTIES_KEY = "savedProperties";
    public static final ERXKey<net.sf.webcat.batchprocessor.BatchResultProperty> savedProperties =
        new ERXKey<net.sf.webcat.batchprocessor.BatchResultProperty>(SAVED_PROPERTIES_KEY);
    // Fetch specifications ---
    public static final String ENTITY_NAME = "BatchResult";


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public BatchResult localInstance(EOEditingContext editingContext)
    {
        return (BatchResult)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this) );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this ).objectForKey( "id" );
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>completedTime</code> value.
     * @return the value of the attribute
     */
    public NSTimestamp completedTime()
    {
        return (NSTimestamp)storedValueForKey( "completedTime" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>completedTime</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setCompletedTime( NSTimestamp value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setCompletedTime("
                + value + "): was " + completedTime() );
        }
        takeStoredValueForKey( value, "completedTime" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>description</code> value.
     * @return the value of the attribute
     */
    public String description()
    {
        return (String)storedValueForKey( "description" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>description</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setDescription( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setDescription("
                + value + "): was " + description() );
        }
        takeStoredValueForKey( value, "description" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isComplete</code> value.
     * @return the value of the attribute
     */
    public boolean isComplete()
    {
        Integer result =
            (Integer)storedValueForKey( "isComplete" );
        return ( result == null )
            ? false
            : ( result.intValue() > 0 );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isComplete</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setIsComplete( boolean value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setIsComplete("
                + value + "): was " + isComplete() );
        }
        Integer actual =
            er.extensions.eof.ERXConstant.integerForInt( value ? 1 : 0 );
            setIsCompleteRaw( actual );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>isComplete</code> value.
     * @return the value of the attribute
     */
    public Integer isCompleteRaw()
    {
        return (Integer)storedValueForKey( "isComplete" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>isComplete</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setIsCompleteRaw( Integer value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setIsCompleteRaw("
                + value + "): was " + isCompleteRaw() );
        }
        takeStoredValueForKey( value, "isComplete" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>batchPlugin</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.batchprocessor.BatchPlugin batchPlugin()
    {
        return (net.sf.webcat.batchprocessor.BatchPlugin)storedValueForKey( "batchPlugin" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>batchPlugin</code>
     * relationship (DO NOT USE--instead, use
     * <code>setBatchPluginRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setBatchPlugin( net.sf.webcat.batchprocessor.BatchPlugin value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setBatchPlugin("
                + value + "): was " + batchPlugin() );
        }
        takeStoredValueForKey( value, "batchPlugin" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>batchPlugin</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setBatchPluginRelationship(
        net.sf.webcat.batchprocessor.BatchPlugin value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setBatchPluginRelationship("
                + value + "): was " + batchPlugin() );
        }
        if ( value == null )
        {
            net.sf.webcat.batchprocessor.BatchPlugin object = batchPlugin();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "batchPlugin" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "batchPlugin" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>objectQuery</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.core.ObjectQuery objectQuery()
    {
        return (net.sf.webcat.core.ObjectQuery)storedValueForKey( "objectQuery" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>objectQuery</code>
     * relationship (DO NOT USE--instead, use
     * <code>setObjectQueryRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setObjectQuery( net.sf.webcat.core.ObjectQuery value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setObjectQuery("
                + value + "): was " + objectQuery() );
        }
        takeStoredValueForKey( value, "objectQuery" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>objectQuery</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setObjectQueryRelationship(
        net.sf.webcat.core.ObjectQuery value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setObjectQueryRelationship("
                + value + "): was " + objectQuery() );
        }
        if ( value == null )
        {
            net.sf.webcat.core.ObjectQuery object = objectQuery();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "objectQuery" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "objectQuery" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>user</code>
     * relationship.
     * @return the entity in the relationship
     */
    public net.sf.webcat.core.User user()
    {
        return (net.sf.webcat.core.User)storedValueForKey( "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship (DO NOT USE--instead, use
     * <code>setUserRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setUser( net.sf.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUser("
                + value + "): was " + user() );
        }
        takeStoredValueForKey( value, "user" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>user</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setUserRelationship(
        net.sf.webcat.core.User value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setUserRelationship("
                + value + "): was " + user() );
        }
        if ( value == null )
        {
            net.sf.webcat.core.User object = user();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "user" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "user" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>batchJobs</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<net.sf.webcat.batchprocessor.BatchJob> batchJobs()
    {
        return (NSArray)storedValueForKey( "batchJobs" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>batchJobs</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setBatchJobs( NSMutableArray<net.sf.webcat.batchprocessor.BatchJob>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setBatchJobs("
                + value + "): was " + batchJobs() );
        }
        takeStoredValueForKey( value, "batchJobs" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>batchJobs</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToBatchJobsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToBatchJobs( net.sf.webcat.batchprocessor.BatchJob value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToBatchJobs("
                + value + "): was " + batchJobs() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchJob> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchJob>)batchJobs();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>batchJobs</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromBatchJobsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromBatchJobs( net.sf.webcat.batchprocessor.BatchJob value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromBatchJobs("
                + value + "): was " + batchJobs() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchJob> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchJob>)batchJobs();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>batchJobs</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToBatchJobsRelationship( net.sf.webcat.batchprocessor.BatchJob value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToBatchJobsRelationship("
                + value + "): was " + batchJobs() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "batchJobs" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>batchJobs</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromBatchJobsRelationship( net.sf.webcat.batchprocessor.BatchJob value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromBatchJobsRelationship("
                + value + "): was " + batchJobs() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "batchJobs" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>batchJobs</code> relationship.
     *
     * @return The new entity
     */
    public net.sf.webcat.batchprocessor.BatchJob createBatchJobsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createBatchJobsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "BatchJob" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "batchJobs" );
        return (net.sf.webcat.batchprocessor.BatchJob)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>batchJobs</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteBatchJobsRelationship( net.sf.webcat.batchprocessor.BatchJob value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteBatchJobsRelationship("
                + value + "): was " + batchJobs() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "batchJobs" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>batchJobs</code> relationship.
     */
    public void deleteAllBatchJobsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllBatchJobsRelationships(): was "
                + batchJobs() );
        }
        for (net.sf.webcat.batchprocessor.BatchJob object : batchJobs())
        {
            deleteBatchJobsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>feedbackSections</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<net.sf.webcat.batchprocessor.BatchFeedbackSection> feedbackSections()
    {
        return (NSArray)storedValueForKey( "feedbackSections" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>feedbackSections</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setFeedbackSections( NSMutableArray<net.sf.webcat.batchprocessor.BatchFeedbackSection>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setFeedbackSections("
                + value + "): was " + feedbackSections() );
        }
        takeStoredValueForKey( value, "feedbackSections" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>feedbackSections</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToFeedbackSectionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToFeedbackSections( net.sf.webcat.batchprocessor.BatchFeedbackSection value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToFeedbackSections("
                + value + "): was " + feedbackSections() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchFeedbackSection> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchFeedbackSection>)feedbackSections();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>feedbackSections</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromFeedbackSectionsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromFeedbackSections( net.sf.webcat.batchprocessor.BatchFeedbackSection value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromFeedbackSections("
                + value + "): was " + feedbackSections() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchFeedbackSection> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchFeedbackSection>)feedbackSections();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>feedbackSections</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToFeedbackSectionsRelationship( net.sf.webcat.batchprocessor.BatchFeedbackSection value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToFeedbackSectionsRelationship("
                + value + "): was " + feedbackSections() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "feedbackSections" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>feedbackSections</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromFeedbackSectionsRelationship( net.sf.webcat.batchprocessor.BatchFeedbackSection value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromFeedbackSectionsRelationship("
                + value + "): was " + feedbackSections() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "feedbackSections" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>feedbackSections</code> relationship.
     *
     * @return The new entity
     */
    public net.sf.webcat.batchprocessor.BatchFeedbackSection createFeedbackSectionsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createFeedbackSectionsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "BatchFeedbackSection" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "feedbackSections" );
        return (net.sf.webcat.batchprocessor.BatchFeedbackSection)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>feedbackSections</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteFeedbackSectionsRelationship( net.sf.webcat.batchprocessor.BatchFeedbackSection value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteFeedbackSectionsRelationship("
                + value + "): was " + feedbackSections() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "feedbackSections" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>feedbackSections</code> relationship.
     */
    public void deleteAllFeedbackSectionsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllFeedbackSectionsRelationships(): was "
                + feedbackSections() );
        }
        for (net.sf.webcat.batchprocessor.BatchFeedbackSection object : feedbackSections())
        {
            deleteFeedbackSectionsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>savedProperties</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<net.sf.webcat.batchprocessor.BatchResultProperty> savedProperties()
    {
        return (NSArray)storedValueForKey( "savedProperties" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>savedProperties</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setSavedProperties( NSMutableArray<net.sf.webcat.batchprocessor.BatchResultProperty>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setSavedProperties("
                + value + "): was " + savedProperties() );
        }
        takeStoredValueForKey( value, "savedProperties" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>savedProperties</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToSavedPropertiesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToSavedProperties( net.sf.webcat.batchprocessor.BatchResultProperty value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToSavedProperties("
                + value + "): was " + savedProperties() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchResultProperty> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchResultProperty>)savedProperties();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>savedProperties</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromSavedPropertiesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromSavedProperties( net.sf.webcat.batchprocessor.BatchResultProperty value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromSavedProperties("
                + value + "): was " + savedProperties() );
        }
        NSMutableArray<net.sf.webcat.batchprocessor.BatchResultProperty> array =
            (NSMutableArray<net.sf.webcat.batchprocessor.BatchResultProperty>)savedProperties();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>savedProperties</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToSavedPropertiesRelationship( net.sf.webcat.batchprocessor.BatchResultProperty value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToSavedPropertiesRelationship("
                + value + "): was " + savedProperties() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "savedProperties" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>savedProperties</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromSavedPropertiesRelationship( net.sf.webcat.batchprocessor.BatchResultProperty value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromSavedPropertiesRelationship("
                + value + "): was " + savedProperties() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "savedProperties" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>savedProperties</code> relationship.
     *
     * @return The new entity
     */
    public net.sf.webcat.batchprocessor.BatchResultProperty createSavedPropertiesRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createSavedPropertiesRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "BatchResultProperty" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "savedProperties" );
        return (net.sf.webcat.batchprocessor.BatchResultProperty)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity that is a member of the
     * <code>savedProperties</code> relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void deleteSavedPropertiesRelationship( net.sf.webcat.batchprocessor.BatchResultProperty value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteSavedPropertiesRelationship("
                + value + "): was " + savedProperties() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "savedProperties" );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>savedProperties</code> relationship.
     */
    public void deleteAllSavedPropertiesRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllSavedPropertiesRelationships(): was "
                + savedProperties() );
        }
        for (net.sf.webcat.batchprocessor.BatchResultProperty object : savedProperties())
        {
            deleteSavedPropertiesRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<BatchResult> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<BatchResult> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<BatchResult> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<BatchResult> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        EOFetchSpecification fspec = new EOFetchSpecification(
            ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static BatchResult firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        NSArray<BatchResult> results =
            objectsMatchingQualifier(context, qualifier, sortOrderings);
        return (results.size() > 0)
            ? results.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static BatchResult uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<BatchResult> results =
            objectsMatchingQualifier(context, qualifier);
        if (results.size() > 1)
        {
            throw new EOUtilities.MoreThanOneException(null);
        }
        return (results.size() > 0)
            ? results.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<BatchResult> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<BatchResult> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static BatchResult firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static BatchResult firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        EOFetchSpecification fspec = new EOFetchSpecification(
            ENTITY_NAME,
            EOQualifier.qualifierToMatchAllValues(keysAndValues),
            sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<BatchResult> result =
            objectsWithFetchSpecification( context, fspec );

        if ( result.count() == 0 )
        {
            return null;
        }
        else
        {
            return result.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static BatchResult uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static BatchResult uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (BatchResult)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    @SuppressWarnings("unchecked")
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger( BatchResult.class );
}
