package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Feb 10, 2007 4:42:15 PM

import java.util.Enumeration;
import java.util.Iterator;

import net.sf.webcat.core.CourseOffering;
import net.sf.webcat.core.WCComponent;
import net.sf.webcat.grader.AssignmentOffering;
import net.sf.webcat.reporter.internal.datamodel.ReferenceEnvironment;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSTimestamp;

public class AssignmentOfferingParameterPanel extends AbstractChooseTypePanel
{
	public NSArray assignmentOfferings;

	public NSMutableArray selectedAssignmentOfferings;

	public int selectedIndex;

	// Used during repetition when generating the visual list
	public AssignmentOffering assignmentOffering;

    public AssignmentOfferingParameterPanel(WOContext context)
    {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context)
    {
    	assignmentOfferings = getChoicesBasedOnDependents();

        selectedAssignmentOfferings = new NSMutableArray();

    	super.appendToResponse(response, context);
    }

    public boolean assignmentOfferingSelected()
    {
    	return selectedAssignmentOfferings.containsObject(assignmentOffering);
    }
    
    public void setAssignmentOfferingSelected(boolean selected)
    {
    	if(selected)
    	{
    		if(!selectedAssignmentOfferings.containsObject(assignmentOffering))
    			selectedAssignmentOfferings.addObject(assignmentOffering);
    	}
    	else
    	{
    		if(selectedAssignmentOfferings.containsObject(assignmentOffering))
    			selectedAssignmentOfferings.removeObject(assignmentOffering);
    	}
    }

    public boolean allAssignmentOfferingsSelected()
    {
    	return (selectedAssignmentOfferings.count() ==
    		assignmentOfferings.count());
    }
    
    public Object currentSelection()
    {
    	if(parameter.multipleSelectionOption())
    	{
    		return selectedAssignmentOfferings;
    	}
    	else
    	{
    		if(selectedIndex == -1)
    			return null;
    		else
    			return assignmentOfferings.objectAtIndex(selectedIndex);
    	}
    }
}