package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Mar 1, 2007 7:24:29 PM

import net.sf.webcat.reporter.internal.datamodel.ReferenceEnvironment;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableDictionary;

public class BooleanParameterPanel extends AbstractParameterPanel
{
	public boolean checked;

    public BooleanParameterPanel(WOContext context)
    {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context)
    {
    	Object result = evaluateWithErrorHandling();

    	if(result != EVALUATION_ERROR)
    	{
    		checked = ((Boolean)result).booleanValue();
    	}

    	super.appendToResponse(response, context);
    }

	@Override
	public Object currentSelection()
	{
		return checked ? Boolean.TRUE : Boolean.FALSE;
	}

	@Override
	public String observeeId()
	{
		return ParameterUIUtils.observeeIdForParameter(parameter);
	}
}