package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Sep 10, 2007 7:02:37 PM

import java.util.BitSet;

import net.sf.webcat.core.WCComponent;
import net.sf.webcat.reporter.queryassistants.IQueryAssistant;
import net.sf.webcat.reporter.queryassistants.AbstractQueryAssistantModel;
import net.sf.webcat.reporter.queryassistants.QueryAssistantDescriptor;
import net.sf.webcat.reporter.queryassistants.QueryAssistantManager;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOAndQualifier;
import com.webobjects.eocontrol.EOKeyComparisonQualifier;
import com.webobjects.eocontrol.EOKeyValueQualifier;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSMutableDictionary;

public class ConstructDataSetQueryPage extends ReporterComponent
{
	public NSArray<ReportDataSet> dataSets;
	
	public int currentDataSetIndex;

	public EOQualifier qualifier;

	public int index;
	
	public NSArray<QueryAssistantDescriptor> queryAssistants;
	
	public QueryAssistantDescriptor queryAssistant;
	
	public String selectedQueryAssistant;

	public AbstractQueryAssistantModel model;

    public ConstructDataSetQueryPage(WOContext context)
    {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context)
    {
    	queryAssistants = QueryAssistantManager.getInstance().
    		assistantsForEntity(dataSet().wcEntityName());

    	ReportQuery query = rollbackQueryForDataSet(dataSet());
    	if(query != null)
    		qualifier = QualifierUtils.qualifierWithEOsForGIDs(
    				query.qualifier(), wcSession().localContext());

    	super.appendToResponse(response, context);
    }
    

    public ReportDataSet dataSet()
    {
    	return dataSets.objectAtIndex(currentDataSetIndex);
    }

    public String linkPartOfQueryAssistantDescription()
    {
    	String desc = queryAssistant.description();
    	int pipe = desc.indexOf('|');
    	
    	if(pipe >= 0)
    		return desc.substring(0, pipe);
    	else
    		return desc;
    }
    
    public String nonLinkPartOfQueryAssistantDescription()
    {
    	String desc = queryAssistant.description();
    	int pipe = desc.indexOf('|');
    	
    	if(pipe >= 0)
    		return desc.substring(pipe + 1);
    	else
    		return desc;
    }

    public WOComponent chooseQueryAssistant()
    {
    	selectedQueryAssistant = queryAssistant.componentName();

    	model = queryAssistant.createModel();
    	model.takeValuesFromQualifier(qualifier);

    	return null;
    }
    
    public WOComponent returnToQueryAssistants()
    {
    	System.out.println("returnToQueryAssistants()");
    	qualifier = model.qualifierFromValues();

    	selectedQueryAssistant = null;
    	model = null;

    	return null;
    }

    public WOComponent returnToPreviousDataSet()
    {
    	if(currentDataSetIndex == 0)
    	{
    		return pageWithName(PickTemplateToGeneratePage.class.getName());
    	}
    	else
    	{
        	ConstructDataSetQueryPage page = (ConstructDataSetQueryPage)
    			pageWithName(ConstructDataSetQueryPage.class.getName());

        	page.takeValueForKey(dataSets, "dataSets");
    		page.takeValueForKey(currentDataSetIndex - 1,
    				"currentDataSetIndex");

    		return page;
    	}
    }

    public WOComponent gotoNextDataSetOrGenerate()
    {
    	System.out.println("gotoNextDataSetOrGenerate()");
    	qualifier = model.qualifierFromValues();

    	EOQualifier gidQualifier = QualifierUtils.qualifierWithGIDsForEOs(
    			qualifier, wcSession().localContext());
   		commitQueryForDataSet(dataSet(), null, gidQualifier);

        if(currentDataSetIndex == dataSets.count() - 1)
        {
        	return pageWithName(GenerationSummaryPage.class.getName());
        }
        else
        {
        	ConstructDataSetQueryPage page = (ConstructDataSetQueryPage)
        		pageWithName(ConstructDataSetQueryPage.class.getName());

        	page.takeValueForKey(dataSets, "dataSets");
        	page.takeValueForKey(currentDataSetIndex + 1,
        			"currentDataSetIndex");

        	return page;
        }
    }
}