package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Feb 10, 2007 1:38:25 PM

import net.sf.webcat.core.CourseOffering;
import net.sf.webcat.core.WCComponent;
import net.sf.webcat.reporter.internal.datamodel.ReferenceEnvironment;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSMutableArray;

public class CourseOfferingParameterPanel extends AbstractChooseTypePanel
{
	public NSArray courseOfferings;

	public NSMutableArray selectedCourseOfferings;

	public int radioSelectedIndex;

	// Used during repetition when generating the visual list
	public CourseOffering courseOffering;

    public CourseOfferingParameterPanel(WOContext context)
    {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context)
    {
    	courseOfferings = getChoicesBasedOnDependents();

        selectedCourseOfferings = new NSMutableArray();
        
        radioSelectedIndex = -1;

    	super.appendToResponse(response, context);
    }

    public boolean courseOfferingSelected()
    {
    	return selectedCourseOfferings.containsObject(courseOffering);
    }
    
    public void setCourseOfferingSelected(boolean selected)
    {
    	if(selected)
    	{
    		if(!selectedCourseOfferings.containsObject(courseOffering))
    			selectedCourseOfferings.addObject(courseOffering);
    	}
    	else
    	{
    		if(selectedCourseOfferings.containsObject(courseOffering))
    			selectedCourseOfferings.removeObject(courseOffering);
    	}
    }

    public boolean allCourseOfferingsSelected()
    {
    	return (selectedCourseOfferings.count() == courseOfferings.count());
    }
    
    public Object currentSelection()
    {
    	if(parameter.multipleSelectionOption())
    	{
    		return selectedCourseOfferings;
    	}
    	else
    	{
    		return courseOfferings.objectAtIndex(radioSelectedIndex);
    	}
    }
}