package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Feb 27, 2007 11:57:06 PM

import java.io.PrintWriter;
import java.io.StringWriter;

import ognl.webobjects.WOOgnl;
import net.sf.webcat.core.WCComponent;
import net.sf.webcat.reporter.internal.datamodel.ReferenceEnvironment;

import com.webobjects.appserver.*;

public class DebugPage extends WCComponent
{
	public String expression;
	public String result;

    public DebugPage(WOContext context)
    {
        super(context);
    }
    
    public void appendToResponse(WOResponse response, WOContext context)
    {
    	super.appendToResponse(response, context);
    }
    
    public WOActionResults updateAction()
    {
    	if(expression != null && expression.length() > 0)
    	{
    		ReferenceEnvironment env = new ReferenceEnvironment(null, null);
    		
    		try
    		{
    			Object res = env.evaluate(expression);
    			
    			if(res == null)
    				result = "<null>";
    			else
    				result = res.getClass().getName() + ": " + res.toString();
    		}
    		catch(Exception e)
    		{
    			StringWriter sw = new StringWriter();
    			PrintWriter pw = new PrintWriter(sw);
    			e.printStackTrace(pw);
    			pw.flush();
    			result = sw.toString();
    		}
    	}
    	
    	return null;
    }
}