package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Feb 27, 2007 11:57:06 PM

import java.io.PrintWriter;
import java.io.StringWriter;

import ognl.webobjects.WOOgnl;
import net.sf.webcat.core.WCComponent;
import net.sf.webcat.grader.Submission;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOFetchSpecification;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSMutableDictionary;

import er.extensions.ERXEOControlUtilities;

public class DebugPage extends ReporterComponent
{
	public NSArray<Submission> results;
	
	public Submission result;

	public NSMutableArray<String> columns;
	
	public String column;
	
	public int index;
	
    public DebugPage(WOContext context)
    {
        super(context);
    }
    
    public void appendToResponse(WOResponse response, WOContext context)
    {
    	columns = new NSMutableArray<String>();
    	columns.addObject("user.userName");
    	columns.addObject("result.finalScore");
    	columns.addObject("assignmentOffering.courseOffering.compactName");
    	columns.addObject("assignmentOffering.assignment.titleString");

    	String uuid = dataSetUuidsInSession().objectAtIndex(0);
    	System.out.println("Getting qualifier for dataset " + uuid);
 /*   	EOQualifier q = qualifierForDataSetUuidInSession(uuid);

    	// Partition qualifier into fetch and non-fetch.
    	EOQualifier[] quals = QualifierUtils.partitionQualifier(q, "Submission");
    	
    	results = ERXEOControlUtilities.objectsWithQualifier(
    			wcSession().localContext(), "Submission", quals[0], null, false);
    	
    	if(quals[1] != null)
    	{
    		results = EOQualifier.filteredArrayWithQualifier(results, quals[1]);
    	}
*/
    	super.appendToResponse(response, context);
    }
    
    public String currentRowColumnValue()
    {
    	try
    	{
    		return result.valueForKeyPath(column).toString();
    	}
    	catch(Exception e)
    	{
    		return "<error>";
    	}
    }
}