package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Jan 30, 2007 2:48:49 PM

import com.webobjects.appserver.*;

public class DisplayReportPage extends WOComponent {

    public DisplayReportPage(WOContext context) {
        super(context);
    }

}