package net.sf.webcat.reporter;

import net.sf.webcat.core.WCComponent;
import net.sf.webcat.reporter.queryassistants.AbstractQueryAssistantModel;
import net.sf.webcat.reporter.queryassistants.QueryAssistantManager;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSArray;

// Generated by the WOLips Templateengine Plug-in at Dec 11, 2007 12:42:45 PM

public class QueryAssistantHolderPage extends ReporterComponent
{
    public QueryAssistantHolderPage(WOContext context)
    {
        super(context);
    }

    // --- Component bindings -----------------------------

    /**
     * The component name of the query assistant that should be rendered on
     * this page.
     */
    public String queryAssistantComponentName;

    /**
     * The current data set for which a query is being constructed.
     */
    public ReportDataSet dataSet;

    /**
     * The query assistant model (whose specific type corresponds to that of
     * the selected query assistant) that contains information about the query.
     */
    public AbstractQueryAssistantModel model;
    
    /**
     * If this is not null, then the user who created this query will be able
     * to recall it when generating future reports, for convenience.
     */
    public String queryDescription;
}