package net.sf.webcat.reporter;
// Generated by the WOLips Templateengine Plug-in at Mar 27, 2007 4:14:37 PM

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import org.apache.log4j.Logger;

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSData;

public class ReportContentsBlock extends WOComponent
{
	public GeneratedReport generatedReport;
	
    public ReportContentsBlock(WOContext context)
    {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context)
    {
    	String htmlPath = GeneratedReport.renderedResourcePath(
    			generatedReport.uuid(), Reporter.REPORT_ROOT_HTML);
    	File htmlFile = new File(htmlPath);
    	
    	try
    	{
			NSData htmlData = new NSData(new FileInputStream(htmlFile),
					(int)htmlFile.length());
			response.appendContentData(htmlData);
		}
    	catch (IOException e)
		{
    		log.error("An error occurred while reading the rendered report", e);
    		
    		response.appendContentString("<p>There was an error reading the " +
    				"rendered report contents.</p>");
		}
    	
    	super.appendToResponse(response, context);
    }
    
    private static Logger log = Logger.getLogger(ReportContentsBlock.class);
}