/*==========================================================================*\
 |  $Id: WCEditRelationshipPageTemplate.java,v 1.3 2008/10/29 14:16:31 aallowat Exp $
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2008 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package net.sf.webcat.admin;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import er.directtoweb.*;

//-------------------------------------------------------------------------
/**
 * An edit-relationship page generated by the direct-to-web template engine.
 *
 *  @author Stephen Edwards
 *  @version $Id: WCEditRelationshipPageTemplate.java,v 1.3 2008/10/29 14:16:31 aallowat Exp $
 */
public class WCEditRelationshipPageTemplate
    extends er.directtoweb.pages.ERD2WEditRelationshipPage
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new WCEditRelationshipPageTemplate object.
     *
     * @param aContext The context to use
     */
    public WCEditRelationshipPageTemplate( WOContext aContext )
    {
        super( aContext );
    }
}


